resources:
- type: compute.v1.instance
  name: HomeWork
  properties:
      zone: us-central1-f
     machineType: https://www.googleapis.com/compute/v1/projects/[MY_PROJECT]/zones/us-central1-f/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
           sourceImage: mydockerid120/index

    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/[MY_PROJECT]/global/networks/default
  
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
